apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-backup-client
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/instance: {{ .Values.name }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  ownerReferences:
  - apiVersion: druid.gardener.cloud/v1alpha1
    blockOwnerDeletion: false
    controller: true
    kind: Etcd
    name: {{ .Values.name }}
    uid: {{ .Values.uid }}
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/instance: {{ .Values.name }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  ports:
  - name: client
    protocol: TCP
    port: {{ .Values.backup.port }}
    targetPort: {{ .Values.backup.port }}
