apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: etcd-druid
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: system
  labels:
    control-plane: etcd-druid
spec:
  selector:
    matchLabels:
      control-plane: etcd-druid
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: etcd-druid
    spec:
      containers:
      - command:
        - /bin/druid
        args:
        - --enable-leader-election
        name: druid
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
