apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: etcd-druid
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-druid
  namespace: test
  labels:
    control-plane: etcd-druid
spec:
  selector:
    matchLabels:
      control-plane: etcd-druid
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: etcd-druid
    spec:
      containers:
      - command:
        - /bin/druid
        args:
        - --enable-leader-election
        image: eu.gcr.io/gardener-project/gardener/druid:0.1.0-dev
        name: manager
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
